### ISSUE TITLE
Remove question about absolute and relative paths on the web?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/unix-cli-assessment#123]
Tied to ga-wdi-boston/unix-cli#15

**Comment by RealWeeks** [comment]
Addressed in delivery. I wish I had recorded this in an issue, but after speaking with @berziiii I addressed during delivery quite explicitly.

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/unix-cli-diagnostic/commit/c957ea49a428fd70e1ff1422b1090cb9176816fc#commitcomment-20461559
