### ISSUE TITLE
No way of grading #4-6 under "Navigating the Filesystem"

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/unix-cli-assessment#146]
They need to either 1) submit the commands they ran in order to accomplish the task, or 2) do a commit with the temp directory and temp.md file, and then another commit that shows that it is gone.

**Comment by gaand** [comment]
I'm fine with requiring multiple commits to track this.

@ga-wdi-boston/core Is it too early to have them attempt such a thing?  Do they have enough git at this point?

**Comment by BenGitsCode** [comment]
using the history command would work just as well, but i think multiple commits would be good practice for the developers.

As long as the need to add and commit is clear within the instructions, I don't see why it would be too soon.
