### ISSUE TITLE
Question 2's Solution is Missing the Second Part

### ISSUE THREAD

**Issue by bernardlee** [ga-wdi-boston/unix-cli-assessment#199]
Q: Suppose that we're working on a project, and we want to use a font that's being hosted on Google at https://fonts.googleapis.com/css?family=Open+Sans. Is that an absolute or relative path to refer to it? Why?

A: Absolute path

The solution doesn't answer "Why?"

**Comment by tvcrawley** [comment]
This can be closed due to the question being changed (see #123)
