### ISSUE TITLE
Questions lacking spaces for answers

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/unix-cli-assessment#83]
After question 5 there is no place to actually put your answer:
1.  Navigate back up to `cli-diagnostic`, and delete the `temp` directory (with
   `temp.md` inside of it). Use `ls` to show the contents of `cli-diagnostic`
2. was `temp` deleted?
## Absolute and Relative Paths

Open up this file in Atom, and write your answers below (where indicated).
1.  Is `/Users/blah_blah/Desktop` a relative path or an absolute path?
   How do you know?

**Comment by RealWeeks** [comment]
This is intended.  We can tell by the files inside of the repo when submitted.  If a file is not removed correctly it will be there when a pull request is created.

**Comment by jrhorn424** [comment]
@MicFin Any reason you referenced a `wontfix` issue in a PR? Was it a mistake?
