### ISSUE TITLE
No Prerequisites Section

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/unix-cli-assessment#95]
Prerequisites
- unix-cli

**Comment by payne-chris-r** [comment]
https://github.com/ga-wdi-boston/unix-cli

**Comment by RealWeeks** [comment]
@payne-chris-r updated in commit    4c978a1. Okay to close?

**Comment by MicFin** [comment]
@payne-chris-r just repinging, wanted to defer to you for closing to be sure

**Comment by jrhorn424** [comment]
Thanks. Looks good.
